server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #注册中心地址
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
