spring:
  application:
    name: panghu-permission
  profiles:
    active: @profileActive@
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
      	suffix: .html
      	cache: false
      	#设置为传统模式，防止因为严格的语法检测遇到的各种麻烦，例如<html />后习惯不会去加斜杠就会被当做错误检测
      	mode: LEGACYHTML5
feign:
  hystrix:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml     #mapper文件路径
  type-aliases-package: com.panghu.permission.entity   #实体类的包路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#==================== 日志  ============================
logging:
  config: classpath:logback.xml
