server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/panghu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 200
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  # rabbitMq 配置
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: admin
#    password: admin

# redis 配置
#redis:
#  database: 0
#  password: test123
#  host: 192.168.124.22
#  port: 6379
#  time: 0
#  pool:
#    max-idle: 100
#    min-idle: 5
#    max-total: 100
#    max-wait-millis: -1

#项目自定义配置
custom:
